### ISSUE TITLE
Kinesis support?

### ISSUE THREAD

**Issue by jychen7** [kislyuk/domovoi#15]
Hi, I want to use it with Kinesis.
Do we have a proposed plan for it?
Is there anything blocking? I would like to help implement.

https://github.com/kislyuk/domovoi/blob/588a105c2d93f410c52465cee0fa281e34157f7e/domovoi/app.py#L72-L73

**Comment by kislyuk** [comment]
Thanks for your interest. You are welcome to submit a PR. I have not had a use for Kinesis log streams yet but if you do, please go ahead and implement. I am not aware of any blockers.

**Comment by kislyuk** [comment]
I will not be adding this functionality to Domovoi; PRs are welcome.
