### ISSUE TITLE
How to use normal api gateway instead of ALB

### ISSUE THREAD

**Issue by Mellonta** [kislyuk/domovoi#25]
I tried the Chalice way.
```
app.route('/')
def f():
    ...
```
but it causes internal server error

**Comment by kislyuk** [comment]
Domovoi is not Chalice - it does not support the complete underlying feature set of Chalice. (It's probably best if Domovoi disables the route() decorator, actually.)

If you need a lambda to work through API Gateway, at this point you should just use Chalice directly. If you need both an API Gateway lambda and something else Domovoi provides, you should make two apps and deploy them alongside each other.
