### ISSUE TITLE
chalicelib folder is not package and upload automatically

### ISSUE THREAD

**Issue by a3linux** [kislyuk/domovoi#26]
First of all, I am a new user of Domovoi or. Chalice,
with chalice deploy cmd, the folder chalicelib packaged and uploaded to lambda.
But Domovoi deploy cmd did NOT do that folder package or update.
Just want to confirm this is by design or is there any workaround?

**Comment by knowsuchagency** [comment]
I've noticed this as well

**Comment by knowsuchagency** [comment]
apparently you need to rename the directory `domovoilib`

**Comment by kislyuk** [comment]
Correct, you have to use `domovoilib` - this is documented in the Readme file.

**Comment by a3linux** [comment]
Great and will try it.
